name: repo_viewer
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.8.4
  google_fonts: ^4.0.0
  stacked: ^3.4.1
  stacked_services: ^1.3.0
  flutter_json_viewer: ^1.0.1
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  github_sign_in: ^0.0.5-dev.4
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.2.10
  http: ^0.13.4
  dartz: ^0.10.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^2.0.2
  stacked_generator: ^1.5.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: '#FFFFFF' 
  image: assets/images/github_icon.png     