// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      return web;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbL8bxXLLCpGdpCBk0xNYVcAOTcoM5-A',
    appId: '1:365444251467:web:2800f341569f98251972ce',
    messagingSenderId: '365444251467',
    projectId: 'github-json-reviewer',
    authDomain: 'github-json-reviewer.firebaseapp.com',
    storageBucket: 'github-json-reviewer.appspot.com',
    measurementId: 'G-8HG4G1C4HQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB46-ddRE9KxzP8Mobz97yovmzceVGcyrY',
    appId: '1:365444251467:android:ee8fed7ce4f5c43e1972ce',
    messagingSenderId: '365444251467',
    projectId: 'github-json-reviewer',
    storageBucket: 'github-json-reviewer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMygc9gVNNY9d8WW8jQ-nrkx0l2kFZOrc',
    appId: '1:365444251467:ios:376d06b54425fd3f1972ce',
    messagingSenderId: '365444251467',
    projectId: 'github-json-reviewer',
    storageBucket: 'github-json-reviewer.appspot.com',
    iosClientId: '365444251467-1hmt7depti1j3sek6bolk6eakpt12rlg.apps.googleusercontent.com',
    iosBundleId: 'com.example.repoViewer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMygc9gVNNY9d8WW8jQ-nrkx0l2kFZOrc',
    appId: '1:365444251467:ios:253c5772c7a5b90d1972ce',
    messagingSenderId: '365444251467',
    projectId: 'github-json-reviewer',
    storageBucket: 'github-json-reviewer.appspot.com',
    iosClientId: '365444251467-hok796hu2iklj311o22b4oqd1ot6p28m.apps.googleusercontent.com',
    iosBundleId: 'com.example.repoViewer.RunnerTests',
  );
}
